<a href="https://colab.research.google.com/github/RogerHeederer/ForAllPytorch/blob/main/RNN_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
torch.manual_seed(0)

In [9]:
# 차원 설정
input_size = 4 # 캐릭터 한개 당 4 개의 숫자들로 구성되어 있으므로 4차원 input_size가 필요
hidden_size = 2 #히든 사이즈는 입력으로 들어온 4차원 size를, 2차원 size로 만들어 결과를 내겠다는 의미
#히든 스테이트는 RNN 셀을 거쳐 나온 결과물(2차원 size)을 숨겨진 상태로 다음 턴 인풋에 넣어주는 값이라 한다

In [4]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

input_data_np = np.array([[h, e, l, l, o],
                          [e, l, l, o, h],
                          [l, l, o, h, e]],dtype=np.float32)

#      3  x     5     x 4 의 형태를 지님
# 배치사이즈 x 시퀀스 길이 x 캐릭터 차원
# [ 
#   [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,1,0],[0,0,0,1]],
#   [[0,1,0,0],[0,0,1,0],[0,0,1,0],[0,0,0,1],[1,0,0,0]],
#   [[0,0,1,0],[0,0,1,0],[0,0,0,1],[1,0,0,0],[0,1,0,0]]
# ]

# [h,e,l,l,o]
# [e,l,l,o,h]
# [l,l,o,h,e]
# 이 3개의 문장을 하나의 배치로 묶어서 한번에 넣는다 =  배치 사이즈

In [5]:
input_data_np

array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]],

       [[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.]]], dtype=float32)

In [6]:
#넘파이 배열로 만든것을 토치 텐서 형태로 변환
#RNN 모델에 넣어주기 위해서는 토치 텐서로 변환해야 한다.
input_data = torch.Tensor(input_data_np)

In [7]:
input_data #array -> tensor로 변경된 것을 확인

tensor([[[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]],

        [[0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.],
         [1., 0., 0., 0.]],

        [[0., 0., 1., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.],
         [1., 0., 0., 0.],
         [0., 1., 0., 0.]]])

In [16]:
print(input_data.size())

torch.Size([3, 5, 4])


In [10]:
# RNN 모델 선언
# input_size(캐릭터 차원)만 잘 선언해주면, 배치사이즈(3), 시퀀시 길이(5)는 파이토치가 알아서 파악해준다
# output의 배치사이즈 및 시퀀스 길이 또한 input의 조건에 맞춰서 모델이 자동 파악
rnn = torch.nn.RNN(input_size, hidden_size)

In [11]:
rnn

RNN(4, 2)

In [15]:
outputs, _status = rnn(input_data) #아웃풋과 현재 상태값을 전달해줌
print(outputs)
print(outputs.size())

tensor([[[-0.7497, -0.6135],
         [-0.5282, -0.2473],
         [-0.9136, -0.4269],
         [-0.9136, -0.4269],
         [-0.9028,  0.1180]],

        [[-0.5753, -0.0070],
         [-0.9158, -0.2994],
         [-0.9173, -0.1989],
         [-0.9069,  0.3567],
         [-0.7132, -0.4914]],

        [[-0.9077, -0.3205],
         [-0.9134, -0.2154],
         [-0.8990,  0.3294],
         [-0.6904, -0.5155],
         [-0.5614, -0.0318]]], grad_fn=<StackBackward>)
torch.Size([3, 5, 2])
