<a href="https://colab.research.google.com/github/RogerHeederer/ForAllPytorch/blob/main/TensorManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [201]:
import numpy as np
import torch

In [202]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [203]:
print('Rank :', t.ndim)
print('Shape :', t.shape)

Rank : 1
Shape : (7,)


In [204]:
#Element
t[0], t[1]

(0.0, 1.0)

In [205]:
#slicing
t[2:-1]

array([2., 3., 4., 5.])

2D array with numpy

In [206]:
t = np.array([[1., 2., 3.],[4., 5., 6.],[7., 8., 9.],[10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [207]:
print(t.ndim)
print(t.shape)

2
(4, 3)


1D array with PyTorch

In [208]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [209]:
t.dim()

1

In [210]:
t.size(), t.shape

(torch.Size([7]), torch.Size([7]))

2D array with pytorch

In [211]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [212]:
print(t[:, 1])

tensor([ 2.,  5.,  8., 11.])


In [213]:
print(t[:, -1])

tensor([ 3.,  6.,  9., 12.])


In [214]:
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [215]:
print(t[:, 1].size())

torch.Size([4])


Shape, Rank, Axis

In [216]:
t = torch.FloatTensor( [ [[1,2,3,4], 
                          [5,6,7,8], 
                          [9,10,11,12]],
                         [[13,14,15,16], 
                          [17,18,19,20], 
                          [21,22,23,24]] ]
                      )

In [217]:
t.dim()

3

In [218]:
t.size()

torch.Size([2, 3, 4])

In [219]:
t[1, 1, :]

tensor([17., 18., 19., 20.])

In [220]:
t[0, 1, :]

tensor([5., 6., 7., 8.])

Mul v s Matmul

In [221]:
m1 = torch.FloatTensor([[1, 2],[3, 4]])
m2 = torch.FloatTensor([[1],[2]])

In [222]:
m1.shape

torch.Size([2, 2])

In [223]:
m2.shape

torch.Size([2, 1])

In [224]:
#Matmul
print(m1.matmul(m2))

tensor([[ 5.],
        [11.]])


In [225]:
#Multiply
print(m1 * m2)

tensor([[1., 2.],
        [6., 8.]])


Broadcasting

In [226]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

tensor([[5., 5.]])


In [227]:
m1 = torch.FloatTensor([[1,2]]) # 2치원 vector
m2 = torch.FloatTensor([3]) # 1차원 scalar ->  [[3], [3]]
print(m1 + m2)


tensor([[4., 5.]])


In [228]:
# 1 x 2 Vector + 2 x 1 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])

In [229]:
m1.shape

torch.Size([1, 2])

In [230]:
m2.shape

torch.Size([2, 1])

In [231]:
m3 = m1 + m2 #m1이 [[1,2], [1,2]]로 브로드캐스팅
             #m2는 [[3,3], [4,4]]로 브로드캐스팅
m3.shape

torch.Size([2, 2])

In [232]:
print(m3)

tensor([[4., 5.],
        [5., 6.]])


Mean

In [233]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [234]:
t = torch.LongTensor([1,2])
try:
  print(t.mean())
except Exception as exc:
  print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [235]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [236]:
t.mean()

tensor(2.5000)

In [237]:
t.mean(dim=0)

tensor([2., 3.])

In [238]:
t.mean(dim=1)

tensor([1.5000, 3.5000])

In [239]:
t.mean(dim=-1)

tensor([1.5000, 3.5000])

Sum

In [240]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [241]:
print(t.sum())

tensor(10.)


In [242]:
print(t.sum(dim=0))

tensor([4., 6.])


In [243]:
print(t.sum(dim=1))

tensor([3., 7.])


In [244]:
t = torch.FloatTensor([[[1, 2]], [[3, 4]]])
print(t)

tensor([[[1., 2.]],

        [[3., 4.]]])


In [245]:
t.sum(dim=0)

tensor([[4., 6.]])

In [246]:
t.sum(dim=1)

tensor([[1., 2.],
        [3., 4.]])

In [247]:
t.sum(dim=2)

tensor([[3.],
        [7.]])

Max and Argmax

In [248]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [249]:
print(t.max())

tensor(4.)


In [250]:
#dim=0 : 가장 바깥쪽 차원을 지웠을 때, 남은 텐서 중에서 맥스값 리턴
#dim=1 : 가장 바깥쪽 차원의 1칸 앞에 있는 차원 지웠을 때
#위치한 인덱스 값까지 같이 준다.
print(t.max(dim=0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [251]:
print('max: ', t.max(dim=0)[0])

max:  tensor([3., 4.])


In [252]:
print('Argmax: ', t.max(dim=0)[1])

Argmax:  tensor([1, 1])


In [253]:
print(t.max(dim=1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


View

In [254]:
t = np.array(
             [[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]]
             )

ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [255]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [256]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


Squeeze : 차원 축소

In [257]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [258]:
print(ft.squeeze())

tensor([0., 1., 2.])


In [259]:
print(ft.squeeze().shape)

torch.Size([3])


Unsqueeze : 차원 추가

In [260]:
ft = torch.Tensor([0, 1, 2])
print(ft)
print(ft.shape)
print(ft.ndim)

tensor([0., 1., 2.])
torch.Size([3])
1


In [261]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)
print(ft.unsqueeze(0).ndim)

tensor([[0., 1., 2.]])
torch.Size([1, 3])
2


In [262]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)
print(ft.unsqueeze(1).ndim)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
2


In [263]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)
print(ft.unsqueeze(-1).ndim)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
2


In [264]:
ft.view(1, -1)

tensor([[0., 1., 2.]])

Scatter

In [265]:
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt)

tensor([[0],
        [1],
        [2],
        [0]])


In [266]:
one_hot = torch.zeros(4, 3)
one_hot

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [267]:
one_hot.scatter_(1, lt, 1)
print(one_hot)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


Casting

In [268]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [269]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [270]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [271]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


Concatenation

In [272]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [273]:
x

tensor([[1., 2.],
        [3., 4.]])

In [274]:
y

tensor([[5., 6.],
        [7., 8.]])

In [275]:
torch.cat([x,y], dim=0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [276]:
torch.cat([x,y], dim=1)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

Stacking

In [277]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [278]:
# [x,y,z] = [[1,4],[2,5],[3,6]]
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z]).shape)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.Size([3, 2])


In [279]:
print(torch.stack([x,y,z], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [280]:
print(torch.stack([x,y,z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


Ones and Zeros Like

In [281]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [282]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In-place Operation

In [283]:
x = torch.FloatTensor([[1,2], [3,4]])

In [284]:
x

tensor([[1., 2.],
        [3., 4.]])

In [286]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [287]:
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


In [ ]:
m1 = torch.FloatTensor([[1, 2],[3, 4]])
m2 = torch.FloatTensor([[1],[2]])

In [299]:
m1 = torch.FloatTensor([[1, 2],[3, 4]])
print(m1)

tensor([[1., 2.],
        [3., 4.]])


In [303]:
print(m1.matmul(torch.FloatTensor([[1],[2]])))
print(m1)

tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [3., 4.]])


matmul은 In-place Operation 안됨

In [304]:
print(m1.matmul_(torch.FloatTensor([[1],[2]])))
print(m1)

AttributeError: ignored

Miscellaneous ( 여러종류의, 다양한)

In [308]:
for x in zip([1,2,3],[4,5,6]):
  print(x)

(1, 4)
(2, 5)
(3, 6)


In [309]:
for x, y in zip([1,2,3],[4,5,6]):
  print(x)

1
2
3


In [310]:
for x, y in zip([1,2,3],[4,5,6]):
  print(x)
  print(y)

1
4
2
5
3
6


In [312]:
for x, y, z in zip([1,2,3],[4,5,6]):
  print(x)

ValueError: ignored

In [313]:
for x, y, z in zip([1,2,3], [4,5,6], [7,8,9]):
  print(x)

1
2
3


In [314]:
for x, y, z in zip([1,2,3], [4,5,6], [7,8,9]):
  print(x, y, z)

1 4 7
2 5 8
3 6 9
